# NOTES
1. NUMPY
2. PANDAS

In [1]:
import numpy as np

### BASICS of numPY

In [ ]:
a=np.array([1,2,3],dtype='int16')
print(a)
a.dtype

In [ ]:
# get dimensions
a.ndim

In [ ]:
b=np.array([[1,2,3],[8,9,10]])
print(b)
b.ndim

In [ ]:
# get shapes
print(a.shape)
print(b.shape)

In [ ]:
a.nbytes
a.dtype

In [ ]:
# get size
a.itemsize

In [ ]:
# getting specific element [r,c]
x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x[-1,-1])

In [ ]:
# getting row
x[0,:]

In [ ]:
#getting column
x[:,2]

In [ ]:
# more slicing 
x[1,1:4:2]

In [ ]:
# Assigning
x[:,2] = [1,2]
print(x)

In [4]:
# 3-d arrays
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# getting element in 3-d
print(b[0,0,2])
print(b[:,:,0])

In [6]:
# assigning in 3-d
b[0,:,:]=[[7,8,9],[10,11,12]]
print(b)

[[[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
# all 0s matrix
np.zeros((2,2,3), dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [20]:
# 1s
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [28]:
# full
np.full(b.shape,2)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [27]:
# full_like(existing arrays or not)
np.full_like(b,2)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [33]:
# random elements in array
np.random.rand(2,3)

array([[0.60047483, 0.37302834, 0.06184175],
       [0.95669712, 0.08788055, 0.90471487]])

In [35]:
# random elements in existing
np.random.random_sample(b.shape)

array([[[0.16665722, 0.7017682 , 0.92354705],
        [0.51775037, 0.15069223, 0.85442202]],

       [[0.35273411, 0.16996614, 0.90129455],
        [0.24076745, 0.43521448, 0.40341135]]])

In [49]:
# random generated int array
np.random.randint(0,6,size=(3,3))

array([[0, 0, 2],
       [2, 2, 2],
       [3, 0, 2]])

In [55]:
# repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
